//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bankamatik.cpp
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#include "Bankamatik.h"

void Bankamatik::bankamatik() {

}

