//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bankamatik.h
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#if !defined(_BANKAMATIK_H)
#define _BANKAMATIK_H


class Bankamatik {
public:
	int i;
	void bankamatik();
};

#endif  //_BANKAMATIK_H
