//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Form1.h
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#if !defined(_FORM1_H)
#define _FORM1_H


class Form1 {
public:
	int alýnanPara;
	int para;
	int para1;
	void parayiver();
	void baglan();
	void kisiselBilgiler();
	void butonumunDurum();
	void butonfalse();
	void parafalse();
	void paraGuncelle();
	void banknoguncelle();
	void labeltemizle();
	void paradurumu();
};

#endif  //_FORM1_H
