//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Form1.cpp
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#include "Form1.h"

void Form1::parayiver() {

}

void Form1::baglan() {

}

void Form1::kisiselBilgiler() {

}

void Form1::butonumunDurum() {

}

void Form1::butonfalse() {

}

void Form1::parafalse() {

}

void Form1::paraGuncelle() {

}

void Form1::banknoguncelle() {

}

void Form1::labeltemizle() {

}

void Form1::paradurumu() {

}

