//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Giris.h
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#if !defined(_GIRIS_H)
#define _GIRIS_H


class Giris {
public:
	int kartNo;
	int MüsteriNo;
	void baglan();
	void veriAl();
	void yoneticiVeriAl();
	void giris();
};

#endif  //_GIRIS_H
