//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Giris.cpp
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#include "Giris.h"

void Giris::baglan() {

}

void Giris::veriAl() {

}

void Giris::yoneticiVeriAl() {

}

void Giris::giris() {

}

