//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Müsteri.cpp
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#include "Müsteri.h"

void Müsteri::baglan() {

}

void Müsteri::müsteri() {

}

void Müsteri::kisiselbilgileri() {

}

