//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Müsteri.h
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#if !defined(_MüSTERI_H)
#define _MüSTERI_H


class Müsteri {
public:
	int i;
	void baglan();
	void müsteri();
private:
	void kisiselbilgileri();
};

#endif  //_MüSTERI_H
