//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ParaYatir.h
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#if !defined(_PARAYATIR_H)
#define _PARAYATIR_H


class ParaYatir {
public:
	int i;
	int para;
	void baglan();
	void kisiselbelgeler();
	void paraekle();
	void parayatir();
};

#endif  //_PARAYATIR_H
