//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ParaYatir.cpp
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#include "ParaYatir.h"

void ParaYatir::baglan() {

}

void ParaYatir::kisiselbelgeler() {

}

void ParaYatir::paraekle() {

}

void ParaYatir::parayatir() {

}

