//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Yonetici.h
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#if !defined(_YONETICI_H)
#define _YONETICI_H


class Yonetici {
public:
	int tablo;
	int tablo2;
	int kartno;
	int ad;
	int ad2;
	int soyad2;
	int soyad;
	int yöneticino;
	void baglan();
	void paraDurumu();
	void paraEkle();
	void Yonetici();
};

#endif  //_YONETICI_H
