//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Yonetici.cpp
//  @ Date : 5.12.2017
//  @ Author : 
//
//


#include "Yonetici.h"

void Yonetici::baglan() {

}

void Yonetici::paraDurumu() {

}

void Yonetici::paraEkle() {

}

void Yonetici::Yonetici() {

}

